#[[
  Copyright 2026 Quintauris GmbH
  Licensed under the Apache License, Version 2.0 (the "License").
  https://www.apache.org/licenses/LICENSE-2.0
]]

add_subdirectory(abi)
add_subdirectory(interrupt)
add_subdirectory(plic)
add_subdirectory(aplic)
add_subdirectory(aclint)
add_subdirectory(imsic)
add_subdirectory(clic)
add_subdirectory(memory)
add_subdirectory(semihost)
